version: '3.4'

services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=retail
      - DOCKER_INFLUXDB_INIT_BUCKET=pricing
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=changeme
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token

  retailpricing.handlers:
    image: ${DOCKER_REGISTRY-}retailpricinghandlers
    build:
      context: .
      dockerfile: RetailPricing.Handlers/Dockerfile
    environment:
      - DOCKER_INFLUXDB_ENDPOINT=http://influxdb:8086
      - DOCKER_INFLUXDB_TOKEN=token
